package com.farmermarket.dto.response;

import com.farmermarket.enums.OrderStatus;
import java.time.LocalDateTime;

/**
 * What we SEND BACK to client
 * after placing or getting order
 *
 * We send:
 * {
 *   "id": 1,
 *   "productId": 1,
 *   "productName": "Fresh Coconuts",
 *   "productPrice": 18.0,
 *   "buyerId": 2,
 *   "buyerName": "Suresh Kumar",
 *   "buyerPhone": "9876543211",
 *   "farmerId": 1,
 *   "farmerName": "Ramesh Shetty",
 *   "farmerPhone": "9876543210",
 *   "quantity": 200.0,
 *   "totalPrice": 3600.0,
 *   "message": "Need by Sunday!",
 *   "status": "PENDING",
 *   "createdAt": "2026-03-21"
 * }
 *
 * Notice:
 * Has productName → What was ordered!
 * Has buyerPhone → Farmer can call buyer!
 * Has farmerPhone → Buyer can call farmer!
 * Has totalPrice → quantity x price!
 */
public class OrderResponse {

    // ════════════════════════════
    // FIELDS
    // ════════════════════════════

    /**
     * Order's unique id
     * Generated by database!
     */
    private Long id;

    /**
     * Product details
     * What was ordered!
     */
    private Long productId;
    private String productName;
    private Double productPrice;

    /**
     * Buyer details
     * Who placed the order!
     * Farmer needs to know!
     */
    private Long buyerId;
    private String buyerName;
    private String buyerPhone;

    /**
     * Farmer details
     * Who received the order!
     * Buyer needs to know!
     */
    private Long farmerId;
    private String farmerName;
    private String farmerPhone;

    /**
     * Order details
     */
    private Double quantity;

    /**
     * Total price!
     * quantity x productPrice
     * 200 x 18 = 3600
     */
    private Double totalPrice;

    private String message;

    /**
     * Order status
     * PENDING = waiting for farmer
     * ACCEPTED = farmer said YES
     * REJECTED = farmer said NO
     * COMPLETED = deal done
     */
    private OrderStatus status;

    private LocalDateTime createdAt;

    // ════════════════════════════
    // CONSTRUCTOR
    // ════════════════════════════
    public OrderResponse() {
    }

    // ════════════════════════════
    // GETTERS
    // ════════════════════════════

    public Long getId() {
        return id;
    }

    public Long getProductId() {
        return productId;
    }

    public String getProductName() {
        return productName;
    }

    public Double getProductPrice() {
        return productPrice;
    }

    public Long getBuyerId() {
        return buyerId;
    }

    public String getBuyerName() {
        return buyerName;
    }

    public String getBuyerPhone() {
        return buyerPhone;
    }

    public Long getFarmerId() {
        return farmerId;
    }

    public String getFarmerName() {
        return farmerName;
    }

    public String getFarmerPhone() {
        return farmerPhone;
    }

    public Double getQuantity() {
        return quantity;
    }

    public Double getTotalPrice() {
        return totalPrice;
    }

    public String getMessage() {
        return message;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    // ════════════════════════════
    // SETTERS
    // ════════════════════════════

    public void setId(Long id) {
        this.id = id;
    }

    public void setProductId(
            Long productId) {
        this.productId = productId;
    }

    public void setProductName(
            String productName) {
        this.productName = productName;
    }

    public void setProductPrice(
            Double productPrice) {
        this.productPrice = productPrice;
    }

    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    public void setBuyerName(
            String buyerName) {
        this.buyerName = buyerName;
    }

    public void setBuyerPhone(
            String buyerPhone) {
        this.buyerPhone = buyerPhone;
    }

    public void setFarmerId(
            Long farmerId) {
        this.farmerId = farmerId;
    }

    public void setFarmerName(
            String farmerName) {
        this.farmerName = farmerName;
    }

    public void setFarmerPhone(
            String farmerPhone) {
        this.farmerPhone = farmerPhone;
    }

    public void setQuantity(
            Double quantity) {
        this.quantity = quantity;
    }

    public void setTotalPrice(
            Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    public void setMessage(
            String message) {
        this.message = message;
    }

    public void setStatus(
            OrderStatus status) {
        this.status = status;
    }

    public void setCreatedAt(
            LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}