package com.farmermarket.dto.response;

import com.farmermarket.enums.Category;
import com.farmermarket.enums.ProductStatus;
import java.time.LocalDateTime;

/**
 * What we SEND BACK to client
 * after creating or getting listing
 *
 * We send:
 * {
 *   "id": 1,
 *   "farmerName": "Ramesh Shetty",
 *   "farmerPhone": "9876543210",
 *   "name": "Fresh Coconuts",
 *   "category": "COCONUT",
 *   "description": "Good quality",
 *   "quantity": 500.0,
 *   "unit": "pieces",
 *   "price": 18.0,
 *   "location": "Puttur",
 *   "district": "Dakshina Kannada",
 *   "status": "ACTIVE",
 *   "createdAt": "2026-03-21"
 * }
 *
 * Notice:
 * We include farmerName and farmerPhone!
 * So buyer can contact farmer directly!
 * That is the whole point of our app!
 */
public class ProductResponse {

    // ════════════════════════════
    // FIELDS
    // ════════════════════════════

    /**
     * Product listing id
     * Generated by database!
     */
    private Long id;

    /**
     * Farmer details
     * Buyer needs to know
     * WHO is selling!
     * So buyer can contact farmer!
     */
    private Long farmerId;
    private String farmerName;
    private String farmerPhone;

    /**
     * Product details
     */
    private String name;
    private Category category;
    private String description;
    private Double quantity;
    private String unit;
    private Double price;
    private String location;
    private String district;

    /**
     * Status of listing
     * ACTIVE = available to buy
     * SOLD = already sold
     * EXPIRED = listing expired
     */
    private ProductStatus status;

    /**
     * When listing was created
     * Auto set by Hibernate!
     */
    private LocalDateTime createdAt;

    // ════════════════════════════
    // CONSTRUCTOR
    // ════════════════════════════
    public ProductResponse() {
    }

    // ════════════════════════════
    // GETTERS
    // Jackson uses these to
    // convert Java → JSON!
    // ════════════════════════════

    public Long getId() {
        return id;
    }

    public Long getFarmerId() {
        return farmerId;
    }

    public String getFarmerName() {
        return farmerName;
    }

    public String getFarmerPhone() {
        return farmerPhone;
    }

    public String getName() {
        return name;
    }

    public Category getCategory() {
        return category;
    }

    public String getDescription() {
        return description;
    }

    public Double getQuantity() {
        return quantity;
    }

    public String getUnit() {
        return unit;
    }

    public Double getPrice() {
        return price;
    }

    public String getLocation() {
        return location;
    }

    public String getDistrict() {
        return district;
    }

    public ProductStatus getStatus() {
        return status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    // ════════════════════════════
    // SETTERS
    // Service uses these to
    // fill this object!
    // ════════════════════════════

    public void setId(Long id) {
        this.id = id;
    }

    public void setFarmerId(Long farmerId) {
        this.farmerId = farmerId;
    }

    public void setFarmerName(
            String farmerName) {
        this.farmerName = farmerName;
    }

    public void setFarmerPhone(
            String farmerPhone) {
        this.farmerPhone = farmerPhone;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCategory(
            Category category) {
        this.category = category;
    }

    public void setDescription(
            String description) {
        this.description = description;
    }

    public void setQuantity(
            Double quantity) {
        this.quantity = quantity;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public void setLocation(
            String location) {
        this.location = location;
    }

    public void setDistrict(
            String district) {
        this.district = district;
    }

    public void setStatus(
            ProductStatus status) {
        this.status = status;
    }

    public void setCreatedAt(
            LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
